# Numpy

## Numpy Library
*Numpy*, conosciuta anche come **Numerical Python** è una libreria per il calcolo scientifico in Python. 
Fornisce *array multi-dimensionali* con potenti funzionalità. Tutte le operazioni di Numpy sono **operazioni vettoriali**, ciò vuol dire che agisco su un insieme di vettori. Libreria scritta in *C*, in modo da avere un enorme vantaggio in termini di efficenza.

### OpenCV
OpenCV-Python utilizza *Numpy* per memorizzare e operare sulla maggior parte dei dati. Le immagini sono suddivise in canali e vengono rappresentate semplicemente come array tridimensionali (un canale per ogni colore). 

#### Importare NUMPY

In [2]:
import numpy as np
print(np.__version__)

1.24.1


### Array 
Gli array che vengono forniti dalla libreria, sono caratterizzati dal fatto che sono array dello stesso tipo (Es: array di interi 32 bit) memorizzati in modo contiguo. 

Implementa un **array multidimensionale omogeneo**, e ci sono diversi attributi per manipolare tale array:
1. **ndim**: Il numero di dimensioni, chiamati anche assi(axes)
2. **shape**: Una tupla di interi che indica il numero di elementi lungo ciascuna dimensione
3. **size**: Il numero totale di elementi dell'array
4. **dtype**: Il tipo degli elementi
5. **itemsize**: La dimensione in byte di ogni elemento
6. **min()**: ottenere il valore minore
7. **max()**: ottenere il valore maggiore
8. **sum()**: ritorna la somma di tutti i valori   

In [3]:
a = np.array([1,2,3])
print('type: ', type(a))
print('ndime:', a.ndim)

type:  <class 'numpy.ndarray'>
ndime: 1


In [6]:
a = np.array([2,3,5])
print(a.ndim, a.shape, a.dtype, a.itemsize)

a = np.array([2,3,5], np.uint8)
print(a.ndim, a.shape, a.dtype, a.itemsize)

a = np.array([[0, 1, 2],[3, 4, 5], [6, 7, 8]])
print(a.ndim, a.shape, a.dtype, a.itemsize)

1 (3,) int64 8
1 (3,) uint8 1
2 (3, 3) int64 8


### Utilizzare le funzioni di Numpy per creare array

1. **empty(dim)**: realizza un array di dimensione *dim*, senza inizializzare i valori, troveremo quindi valori random letti dalla memoria
2. **zeros(dim)**: realizza un array di dimensione *dim* con tutti zeri
3. **ones(dim)**: realizza un array di dimensione *dim* con tutti uni
4. **arange(start, stop, step)**: realizza un array con valori da start a stop-1 con passo *step*
5. **identity(dim)**: realizza una matrice *identità* dim x dim
6. **random(dim**): realizza una matrice di valori random

In [7]:
a = np.empty((2,7), np.int16)
print(a)

[[  3068  24658  32614      0      0      0      0]
 [     0 -31392  23056  21957      0  22816  23200]]


In [ ]:
a = np.zeros((2,2))
print(a)

In [ ]:
a = np.ones((2,2))
print(a)

In [8]:
a = np.arange(100, 120, 2)
print(a)

[100 102 104 106 108 110 112 114 116 118]


In [10]:
a = np.identity(2)
print(a)

[[1. 0.]
 [0. 1.]]


### Operazioni di base

Qualsiasi operazione che viene svolta, è una operazione **VETTORIALE**, di conseguenza qualsiasi operazione si ripercuote su tutto il vettore.

* **a-b**: esegue la sottrazione tra ogni elemento
* **a\*\*2**: esegue l'elevamento a potenza di ogni singolo elemento 

In [12]:
a = np.array([25, 36, 49, 64])
b = np.arange(4)
print(b)

c = a-b
print(c)

[0 1 2 3]


array([25, 35, 47, 61])

In [13]:
print(b**2)

[0 1 4 9]


In [14]:
print(a < 37)

[ True  True False False]


#### Prodotto

Il prodotto viene fatto come prodotto matriciale attraverso l'operatore **@** (riga x colonna) nel caso in cui si volesse avere il prodotto tra tutti gli elementi basta usare il valore **\***. 

In [17]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

print(A * B)
print(A @ B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


### Operatori di Casting

Per effettuare il cambio di valore degli elementi di un array basta richiamre la funzione **oggetto.astype(type)**.

In [18]:
a = a.astype(np.uint32)

In [20]:
a = np.random.random((2,3))
print(a)
print(a.min())
print(a.max())

[[0.45764187 0.73852132 0.05192533]
 [0.0711221  0.42628099 0.5526592 ]]
0.05192532781536052
0.7385213244099484


In [21]:
print(a.sum(axis=1)) # somma di riga
print(a.sum(axis=0)) #somma di colonna

[1.24808853 1.05006229]
[0.52876398 1.16480232 0.60458453]
